# Generated by Django 4.0.3 on 2022-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='profinterests',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
