# Generated by Django 5.0 on 2023-12-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0002_psychologist_profinterests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologist',
            options={'verbose_name': 'Психологи', 'verbose_name_plural': 'Психологи'},
        ),
        migrations.AlterModelOptions(
            name='urltoonlineconsultation',
            options={'verbose_name': 'Ссылки для онлайн консультаций', 'verbose_name_plural': 'Ссылки для онлайн консультаций'},
        ),
    ]
