# Generated by Django 5.0 on 2023-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentspost',
            name='grade',
            field=models.CharField(choices=[('', '-----'), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], help_text='оценка', max_length=10),
        ),
    ]
