# Generated by Django 5.0 on 2023-12-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0002_userextended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='right',
            options={'verbose_name': 'Права', 'verbose_name_plural': 'Права'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userright',
            options={'verbose_name': 'Права пользователя', 'verbose_name_plural': 'Права пользователя'},
        ),
    ]
