# Generated by Django 4.0.3 on 2022-05-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0001_initial'),
        ('Consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('очно', 'очно'), ('онлайн', 'онлайн')], default='очно', help_text='очно/онлайн', max_length=10)),
                ('id_consultation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Consultation.consultation')),
                ('id_user', models.ForeignKey(blank=True, help_text='Если поле пустое, значит записался неавторизованный пользователь', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Authorization.user')),
            ],
        ),
    ]
