# Generated by Django 5.0 on 2023-12-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0003_consultation_is_busy_alter_appointment_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Запись'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультация'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адрес'},
        ),
    ]
